[package]
name = "bar_calendar"
version = "0.1.0"
authors = ["devensiv <devensiv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dirs = "3.0.2"
